apiVersion : apps/v1
kind: Deployment
metadata:
  name: kairoboniweatherapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kairoboniweatherapi
  template:
    metadata:
      labels:
        app: kairoboniweatherapi 
    spec:
      containers:
        - name: kairoboniweatherapi 
          image: aggregatorapiregistry.azurecr.io/kairoboniweatherapi
          ports:
          - containerPort: 80